### ISSUE TITLE
Pause With Space Bar

### ISSUE THREAD

**Issue by infosisio** [artemanufrij/playmymusic#126]
This is available in most players and is useful to those who are used to it.

**Comment by artemanufrij** [comment]
@infosisio could you test current master branch please?

**Comment by artemanufrij** [comment]
@infosisio could you test it again, please?

**Comment by Maccer1** [comment]
Not OP but I've tested it. Play/Pause with spacebar works, but if you mouseclick to pause and then use the spacebar to play it gets stuck (plays for a second and pauses again). The same happens if you click to play and then try to pause with the spacebar.

I've also found that clicking Next and then pressing spacebar it simulates a second Next click while also doing the thing I've mentioned above. The same happens with the "Previous song" button.

**Comment by infosisio** [comment]
@artemanufrij Just tested it, works !

**Comment by artemanufrij** [comment]
@Maccer1 @infosisio guys, check current master branch please.

PS: if you click to title bar (song name) it jumps directly to playing song

**Comment by Maccer1** [comment]
I've updated Melody but the same issues I mentioned earlier still happen. Moreover if I click the song name it doesn't jump to it. If I double click then the window resizes but nothing more.
I'm nearly sure I've updated it correctly since another bug I've reported has just been solved so I don't know what's happening :/

Also maybe I should mention that I'm using Juno beta so maybe some things could differ if you are using Loki.

**Comment by artemanufrij** [comment]
@Maccer1 I can't reproduce it. Could you describe it step by step?

**Comment by artemanufrij** [comment]
@Maccer1 I have it.

**Comment by artemanufrij** [comment]
can be tested

**Comment by Maccer1** [comment]
I made a video if you need more clarification, but yeah it still happens (as of 15 min ago)

**Comment by artemanufrij** [comment]
@Maccer1 yes, please! but with last master branch...

**Comment by Maccer1** [comment]
Alright. Now it's partially solved. The only issue that persists is clicking pause/play and then using the spacebar to do the same. It continues to stop the song after 1 second.

Playing another song solves this issue (until the next time you click pause/play).

**Comment by Maccer1** [comment]
Yes! It's perfect now :1st_place_medal:

**Comment by artemanufrij** [comment]
thanks for testing!
