### ISSUE TITLE
If there's a Folder.jpg file in a folder, all the songs in it get that as Album Art

### ISSUE THREAD

**Issue by 413Michele** [artemanufrij/playmymusic#21]
I have a "Various" folder in which I put a lot of songs from different artists, and when I imported my music in the app they all had the Album Art of a single song.

I found that the Folder.jpg file in that folder was the one of that song and when I removed it (the Folder.jpg file), all the other songs got the right picture.

**Comment by artemanufrij** [comment]
@413Michele thank you for your feedback.

following file names have priority: `'cover.jpg', 'Cover.jpg', 'cover.png', 'Cover.png', 'album.jpg', 'Album.jpg', 'album.png', 'Album.png', 'folder.jpg', 'Folder.jpg', 'folder.png', 'Folder.png', 'front.jpg', 'Front.jpg', 'front.png', 'Front.png'` _(You can see and edit it in dconf)_. The reason is the performance. It's faster to load cover from file instead from ID3 tag.

**Comment by artemanufrij** [comment]
I hope I could help you.

**Comment by 413Michele** [comment]
I can see your point, those files were probably remnants of Windows Media Player auto download from years ago. Thinking about it, it's really a limit case

**Comment by artemanufrij** [comment]
@413Michele do you mean only Folder.jpg? What about other file names?

**Comment by 413Michele** [comment]
@artemanufrij
I'm not sure what you mean, but the Folder.jpg files in my music folders were almost certainly created by WMP, in Windows they are even hidden

**Comment by artemanufrij** [comment]
If you mean we should remove only folder.jpg so I'm agree either you...
