### ISSUE TITLE
[PLAYLIST]: add playlist support

### ISSUE THREAD

**Issue by artemanufrij** [artemanufrij/playmymusic#7]

**Comment by k4r7u** [comment]
Is this intended to be like the playlist feature in VLC?
This is currently the only reason why I am still using VLC instead of playmymusic or elementary music.
I have a lot of music on my NAS perfectly sorted in a good folder structure, which is not always available to my Laptop. Therefore a library maintained by a music app is not working for me. It would be nice to be able to just drag folders to the music player without it being added to a library.

**Comment by artemanufrij** [comment]
Hey @k4r7u, you can already import music files into Music Player. `Options` -> `Import Music...`. It's an import of path's into database and not a file copy.

**Comment by k4r7u** [comment]
Yes, I am aware of that. The issue for me is, that when my NAS is not available, I have a really big library not available to me, but shown in the player. Therefore, I would like to just drag and drop a folder containing for example an Album to a playlist view. Then, I can just remove the tracks again from the playlist view. 
So, basically my library is folder based and not based on id3 tags. I just drop whatever I want to listen to to a temporary playlist. That way I am not depended on a local managed library, but can access the folder structure from whatever device and platform I like.
I am aware, that most people prefer a locally managed library based on id3 tags and not on the folder structure.
Nevertheless this would be a really cool feature.

**Comment by artemanufrij** [comment]
First version of playlist was shipped.

For other bugs or feature requests open a new issue please.
